"""
BRD (Business Requirements Document) Generator Module
=====================================================

Generates professional Business Requirements Documents from analysis data
in multiple formats: PDF, DOCX, TXT, PNG

Includes BRDFormatter for formal Business Requirements Document template generation.
"""

import json
import io
from datetime import datetime
from typing import Dict, Any, Optional, List, Tuple
import logging

logger = logging.getLogger(__name__)


class BRDGenerator:
    """Generate professional BRD documents from analysis data"""
    
    BRD_VERSION = "1.0"
    
    def __init__(self, analysis_data: Dict[str, Any]):
        """
        Initialize BRD generator with analysis data
        
        Args:
            analysis_data: Dict containing analysis results from AI engine
        """
        self.analysis_data = analysis_data
        self.generated_at = datetime.now().strftime("%B %d, %Y at %H:%M:%S")
        
        logger.info("BRD Generator initialized")
    
    def generate_txt(self) -> str:
        """Generate BRD as plain text format"""
        logger.info("Generating BRD in TXT format")
        
        content = self._build_brd_structure()
        
        txt_output = f"""
{"="*80}
STRUCTIFY BUSINESS REQUIREMENTS DOCUMENT (BRD)
{"="*80}

Generated: {self.generated_at}
BRD Version: {self.BRD_VERSION}

{"="*80}
1. EXECUTIVE SUMMARY
{"="*80}

{content['executive_summary']}

{"="*80}
2. IDEA OVERVIEW
{"="*80}

Business Idea: {content['idea']}

Description:
{content['full_description']}

{"="*80}
3. MARKET ANALYSIS
{"="*80}

Target Market: {content['target_market']}

Market Assessment:
{content['market_assessment']}

Domain Classification: {', '.join(content['domain_tags'])}

{"="*80}
4. PROBLEM DEFINITION
{"="*80}

Problem Statement: {content['problem_statement']}

Detailed Analysis:
{content['problem_analysis']}

{"="*80}
5. AI COMPATIBILITY ASSESSMENT
{"="*80}

Compatibility Score: {content['compatibility_score']}/100

Score Interpretation:
{content['score_interpretation']}

Assessment:
{content['analysis_text']}

{"="*80}
6. RISK ASSESSMENT
{"="*80}

Risk Level: {content['risk_level'].upper()}

Risk Analysis:
{content['risk_analysis']}

{"="*80}
7. IMPROVEMENT RECOMMENDATIONS
{"="*80}

The following recommendations are provided to strengthen the business concept:

"""
        
        for idx, suggestion in enumerate(content['improvement_suggestions'], 1):
            txt_output += f"\n{idx}. {suggestion}\n"
        
        txt_output += f"""

{"="*80}
8. NEXT STEPS
{"="*80}

1. Conduct detailed market validation research
2. Develop comprehensive business plan
3. Create MVP prototype design
4. Identify funding requirements
5. Build founding team
6. Develop go-to-market strategy
7. Establish key success metrics

{"="*80}
DOCUMENT INFORMATION
{"="*80}

This BRD was generated by Structify AI Analysis Engine.
All content is based on the analysis of your business concept.
For updates or modifications, please regenerate the BRD with updated information.

Structify - AI-Powered Business Requirements Document Generation
https://structify.io

{"="*80}
END OF DOCUMENT
{"="*80}
"""
        
        return txt_output
    
    def generate_json(self) -> str:
        """Generate BRD as structured JSON format"""
        logger.info("Generating BRD in JSON format")
        
        content = self._build_brd_structure()
        
        brd_json = {
            "metadata": {
                "format": "BRD",
                "version": self.BRD_VERSION,
                "generated_at": self.generated_at,
                "generator": "Structify BRD Engine"
            },
            "executive_summary": content['executive_summary'],
            "idea": {
                "title": content['idea'],
                "description": content['full_description']
            },
            "market_analysis": {
                "target_market": content['target_market'],
                "assessment": content['market_assessment'],
                "domain_tags": content['domain_tags']
            },
            "problem_statement": {
                "statement": content['problem_statement'],
                "analysis": content['problem_analysis']
            },
            "ai_assessment": {
                "compatibility_score": content['compatibility_score'],
                "score_interpretation": content['score_interpretation'],
                "detailed_analysis": content['analysis_text']
            },
            "risk_assessment": {
                "risk_level": content['risk_level'],
                "analysis": content['risk_analysis']
            },
            "recommendations": content['improvement_suggestions'],
            "next_steps": [
                "Conduct detailed market validation research",
                "Develop comprehensive business plan",
                "Create MVP prototype design",
                "Identify funding requirements",
                "Build founding team",
                "Develop go-to-market strategy",
                "Establish key success metrics"
            ]
        }
        
        return json.dumps(brd_json, indent=2)
    
    def _build_brd_structure(self) -> Dict[str, Any]:
        """Build complete BRD structure from analysis data"""
        
        idea = self.analysis_data.get('idea', 'Unnamed Business Idea')
        target_market = self.analysis_data.get('target_market', 'Unspecified Market')
        problem = self.analysis_data.get('problem_statement', 'Not Specified')
        score = self.analysis_data.get('compatibility_score', 50)
        risk = self.analysis_data.get('risk_level', 'medium')
        analysis = self.analysis_data.get('analysis', 'Analysis not available')
        suggestions = self.analysis_data.get('improvement_suggestions', [])
        tags = self.analysis_data.get('domain_tags', [])
        
        # Build executive summary
        exec_summary = f"""
This Business Requirements Document (BRD) outlines the analysis of a business concept: "{idea}"

The proposed concept targets the {target_market} market segment and aims to address:
"{problem}"

Based on comprehensive AI analysis, the business concept has received a compatibility score of {score}/100,
indicating a {self._score_rating(score)} viability rating. The identified business risk level is classified as {risk.upper()}.

This document provides a structured overview of the business concept, market opportunity, competitive landscape,
and strategic recommendations for development and market entry.
"""
        
        # Build market assessment
        market_assessment = f"""
The {target_market} market represents the primary target for this business concept.

Market Characteristics:
- Industry Sectors: {', '.join(tags) if tags else 'General Business'}
- Content Focus: {target_market}
- Market Opportunity: Based on the problem statement provided, there is potential demand

Addressable Market:
The market segment consists of entities and individuals within the {target_market} category
who experience the identified problem and would benefit from the proposed solution.
"""
        
        # Build problem analysis
        problem_analysis = f"""
Core Problem:
{problem}

Market Gap:
The identified problem represents a genuine market opportunity where customers actively seek solutions.
The widespread nature of this challenge suggests a viable business opportunity.

Customer Pain Points:
- Time inefficiency
- Resource constraints
- Lack of adequate solutions in market
- Growing need for innovation

The depth and breadth of this problem indicates strong demand potential for effective solutions.
"""
        
        # Build risk analysis
        risk_desc = {
            "low": "Low risk indicates that the business concept is based on established market dynamics with proven demand. The business model aligns with current market trends and has identifiable customer segments.",
            "medium": "Medium risk indicates that while the concept has merit and addresses real problems, there are factors requiring careful attention. Success will depend on execution quality, market timing, and competitive differentiation.",
            "high": "High risk indicates that the business concept operates in unproven or highly competitive markets. Significant market research and validation are required before full implementation."
        }
        
        risk_analysis = risk_desc.get(risk, "Risk assessment not available")
        
        # Score interpretation
        score_interp = self._interpret_score(score)
        
        return {
            'executive_summary': exec_summary,
            'idea': idea,
            'full_description': f"Business Idea: {idea}\n\nTarget Market: {target_market}\n\nProblem Addressed: {problem}",
            'target_market': target_market,
            'market_assessment': market_assessment,
            'domain_tags': tags,
            'problem_statement': problem,
            'problem_analysis': problem_analysis,
            'compatibility_score': score,
            'score_interpretation': score_interp,
            'analysis_text': analysis,
            'risk_level': risk,
            'risk_analysis': risk_analysis,
            'improvement_suggestions': suggestions
        }
    
    def _score_rating(self, score: int) -> str:
        """Convert score to rating"""
        if score >= 80:
            return "Excellent"
        elif score >= 60:
            return "Good"
        elif score >= 40:
            return "Fair"
        else:
            return "Needs Development"
    
    def _interpret_score(self, score: int) -> str:
        """Provide detailed score interpretation"""
        if score >= 80:
            return f"""
The compatibility score of {score}/100 indicates EXCELLENT viability.

This score reflects:
✓ Strong market alignment
✓ Clear problem-solution fit
✓ Viable business model potential
✓ Identified market opportunity
✓ Competitive differentiation possible

This business concept shows strong potential for success with proper execution.
"""
        elif score >= 60:
            return f"""
The compatibility score of {score}/100 indicates GOOD viability.

This score reflects:
✓ Solid market opportunity
✓ Addressable problem
✓ Reasonable business model
✓ Identifiable customer base
⚠ Requires execution focus

Success depends on strong execution and market validation.
"""
        elif score >= 40:
            return f"""
The compatibility score of {score}/100 indicates FAIR viability.

This score reflects:
✓ Market potential exists
✓ Problem is addressable
⚠ Competitive challenges
⚠ Execution complexity
⚠ Market validation needed

Significant market research and validation recommended.
"""
        else:
            return f"""
The compatibility score of {score}/100 indicates NEEDS DEVELOPMENT.

This score reflects:
⚠ Unclear market fit
⚠ Unproven demand
⚠ Execution risks
⚠ Market validation critical

Comprehensive market research and concept refinement required.
"""


class BRDExporter:
    """Export BRD to various file formats"""
    
    @staticmethod
    def to_pdf(brd_content: str) -> io.BytesIO:
        """Convert BRD to PDF format"""
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
            from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
            
            logger.info("Generating PDF format")
            
            # Create PDF buffer
            pdf_buffer = io.BytesIO()
            doc = SimpleDocTemplate(pdf_buffer, pagesize=letter)
            
            # Define styles
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor='#3b82f6',
                spaceAfter=30,
                alignment=TA_CENTER
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=14,
                textColor='#1e3a8a',
                spaceAfter=12,
                spaceBefore=12
            )
            
            body_style = ParagraphStyle(
                'CustomBody',
                parent=styles['BodyText'],
                fontSize=11,
                alignment=TA_JUSTIFY,
                spaceAfter=12
            )
            
            # Build content
            story = []
            
            # Title
            story.append(Paragraph("STRUCTIFY BUSINESS REQUIREMENTS DOCUMENT", title_style))
            story.append(Spacer(1, 0.3*inch))
            
            # Content - parse BRD text and add sections
            sections = brd_content.split('\n\n')
            for section in sections:
                if section.strip():
                    if '=' in section:
                        # Section header
                        header_text = section.replace('=', '').strip()
                        if header_text:
                            story.append(Paragraph(header_text, heading_style))
                    else:
                        # Body text
                        story.append(Paragraph(section.strip(), body_style))
                    story.append(Spacer(1, 0.1*inch))
            
            # Build PDF
            doc.build(story)
            pdf_buffer.seek(0)
            
            logger.info("PDF generated successfully")
            return pdf_buffer
            
        except ImportError:
            logger.warning("reportlab not installed, returning text as fallback")
            buffer = io.BytesIO()
            buffer.write(brd_content.encode('utf-8'))
            buffer.seek(0)
            return buffer
    
    @staticmethod
    def to_docx(brd_content: str) -> io.BytesIO:
        """Convert BRD to DOCX (Word) format"""
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor, Inches
            from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
            
            logger.info("Generating DOCX format")
            
            doc = Document()
            
            # Add title
            title = doc.add_heading('STRUCTIFY BUSINESS REQUIREMENTS DOCUMENT', 0)
            title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            
            # Parse content and add to document
            sections = brd_content.split('\n')
            
            current_heading = None
            for line in sections:
                line = line.strip()
                
                if not line:
                    continue
                
                # Check if it's a heading
                if line.startswith('='):
                    continue
                
                # Check for numbered sections
                if any(f"{i}." in line[:5] for i in range(1, 10)):
                    current_heading = line
                    doc.add_heading(line, level=2)
                elif line and not line.startswith('#'):
                    # Regular paragraph
                    if len(line) > 0:
                        p = doc.add_paragraph(line)
                        p.paragraph_format.space_after = Pt(6)
            
            # Save to buffer
            docx_buffer = io.BytesIO()
            doc.save(docx_buffer)
            docx_buffer.seek(0)
            
            logger.info("DOCX generated successfully")
            return docx_buffer
            
        except ImportError:
            logger.warning("python-docx not installed, returning text as fallback")
            buffer = io.BytesIO()
            buffer.write(brd_content.encode('utf-8'))
            buffer.seek(0)
            return buffer
    
    @staticmethod
    def to_text(brd_content: str) -> io.BytesIO:
        """Convert BRD to plain text format"""
        logger.info("Generating TXT format")
        
        buffer = io.BytesIO()
        buffer.write(brd_content.encode('utf-8'))
        buffer.seek(0)
        
        logger.info("TXT generated successfully")
        return buffer
    
    @staticmethod
    def to_image(brd_content: str) -> io.BytesIO:
        """Convert BRD summary to PNG image"""
        try:
            from PIL import Image, ImageDraw, ImageFont
            
            logger.info("Generating PNG image format")
            
            # Create image
            width = 1200
            height = 1600
            background_color = (255, 255, 255)
            text_color = (0, 0, 0)
            
            img = Image.new('RGB', (width, height), background_color)
            draw = ImageDraw.Draw(img)
            
            # Try to use a nice font, fallback to default
            try:
                title_font = ImageFont.truetype("arial.ttf", 32)
                heading_font = ImageFont.truetype("arial.ttf", 20)
                body_font = ImageFont.truetype("arial.ttf", 14)
            except:
                title_font = ImageFont.load_default()
                heading_font = ImageFont.load_default()
                body_font = ImageFont.load_default()
            
            # Add content
            y_position = 50
            line_height = 30
            
            # Title
            draw.text((50, y_position), "STRUCTIFY BRD SUMMARY", fill=(59, 130, 246), font=title_font)
            y_position += 80
            
            # Extract key sections from content
            lines = brd_content.split('\n')
            for line in lines[:50]:  # Limit to first 50 lines to fit in image
                if line.strip() and len(line.strip()) > 0:
                    # Wrap long lines
                    if len(line) > 100:
                        words = line.split()
                        current_line = ""
                        for word in words:
                            if len(current_line) + len(word) < 100:
                                current_line += word + " "
                            else:
                                if current_line:
                                    draw.text((50, y_position), current_line, fill=text_color, font=body_font)
                                    y_position += line_height
                                current_line = word + " "
                        if current_line:
                            draw.text((50, y_position), current_line, fill=text_color, font=body_font)
                            y_position += line_height
                    else:
                        draw.text((50, y_position), line[:120], fill=text_color, font=body_font)
                        y_position += line_height
                    
                    if y_position > height - 100:
                        break
            
            # Save to buffer
            image_buffer = io.BytesIO()
            img.save(image_buffer, format='PNG')
            image_buffer.seek(0)
            
            logger.info("PNG generated successfully")
            return image_buffer
            
        except ImportError:
            logger.warning("Pillow not installed for image generation")
            # Return text as fallback
            buffer = io.BytesIO()
            buffer.write(brd_content.encode('utf-8'))
            buffer.seek(0)
            return buffer


class BRDFormatter:
    """
    Formal Business Requirements Document (BRD) Formatter
    
    Transforms structured analysis data into a formal BRD following
    strict template structure with specific sections, tables, and formatting rules.
    """
    
    def __init__(self, analysis_data: Dict[str, Any]):
        """
        Initialize BRD formatter with analysis data
        
        Args:
            analysis_data: Dict containing analysis results from AI engine
        """
        self.analysis_data = analysis_data
        self.generated_at = datetime.now().strftime("%B %d, %Y")
        logger.info("BRD Formatter initialized")
    
    def generate_formatted_brd(self) -> str:
        """
        Generate formal BRD document in markdown format
        
        Returns:
            str: Formatted BRD following strict template structure
        """
        sections = []
        
        # 1. HEADER METADATA
        sections.append(self._generate_header_metadata())
        
        # 2. EXECUTIVE SUMMARY
        sections.append(self._generate_executive_summary())
        
        # 3. PROJECT OBJECTIVES
        sections.append(self._generate_project_objectives())
        
        # 4. PROJECT SCOPE
        sections.append(self._generate_project_scope())
        
        # 5. BUSINESS REQUIREMENTS (TABLE)
        sections.append(self._generate_business_requirements())
        
        # 6. KEY STAKEHOLDERS (TABLE)
        sections.append(self._generate_key_stakeholders())
        
        # 7. PROJECT CONSTRAINTS (TABLE)
        sections.append(self._generate_project_constraints())
        
        # 8. COST-BENEFIT ANALYSIS (TABLE)
        sections.append(self._generate_cost_benefit_analysis())
        
        return "\n\n".join(sections)
    
    def _generate_header_metadata(self) -> str:
        """Generate header metadata section"""
        project_name = self.analysis_data.get('idea', 'Business Project')
        
        metadata = f"""# BUSINESS REQUIREMENTS DOCUMENT

**Project Name:** {project_name}

**Project Manager:** To be assigned

**Date Submitted:** {self.generated_at}

**Document Status:** Draft"""
        
        return metadata
    
    def _generate_executive_summary(self) -> str:
        """Generate executive summary (5-8 lines, business overview)"""
        idea = self.analysis_data.get('idea', 'Unnamed Business Idea')
        target_market = self.analysis_data.get('target_market', 'Unspecified')
        problem = self.analysis_data.get('problem_statement', 'Not specified')
        score = self.analysis_data.get('compatibility_score', 50)
        
        viability = self._get_viability_rating(score)
        
        summary = f"""## 1. Executive Summary

This document defines the business requirements for {idea}. The project targets the {target_market} market and addresses the critical problem of {problem}. Based on business analysis, the concept demonstrates {viability} market viability with strong potential for operational value creation. The proposed solution will serve identified customer needs within the target market segment. Implementation will focus on measurable business outcomes and sustainable operational improvement. Successful execution requires disciplined market validation and strategic stakeholder alignment."""
        
        return summary
    
    def _generate_project_objectives(self) -> str:
        """Generate project objectives (outcome-focused bullet points)"""
        improvement_suggestions = self.analysis_data.get('improvement_suggestions', [])
        target_market = self.analysis_data.get('target_market', 'target market')
        
        objectives = [
            f"Establish market presence in {target_market}",
            "Deliver measurable customer value proposition",
            "Achieve operational efficiency targets",
            "Reduce identified customer pain points by defined metrics",
            "Build sustainable competitive position"
        ]
        
        # Add improvement-based objectives
        if improvement_suggestions:
            if len(improvement_suggestions) > 0:
                objectives.append(improvement_suggestions[0].replace('Improve', 'Establish').replace('Enhance', 'Develop'))
        
        objectives_text = "## 2. Project Objectives\n\n"
        for obj in objectives:
            objectives_text += f"- {obj}\n"
        
        return objectives_text.rstrip()
    
    def _generate_project_scope(self) -> str:
        """Generate project scope with IN SCOPE and OUT OF SCOPE subsections"""
        target_market = self.analysis_data.get('target_market', 'target market')
        
        in_scope = f"""## 3. Project Scope

### IN SCOPE

- System analysis and requirements definition for {target_market}
- Identification and documentation of customer needs
- Definition of functional behaviors and system responsibilities
- Market opportunity assessment and validation
- Stakeholder requirement collection and analysis
- Business process mapping and workflow definition
- Success metrics and performance indicators"""
        
        out_of_scope = """

### OUT OF SCOPE

- System implementation and development activities
- Technical architecture and infrastructure design
- User interface design and interaction specifications
- Legacy system integration and data migration
- Production deployment and operational support
- Third-party technology selection and integration
- Training program development and delivery"""
        
        return in_scope + out_of_scope
    
    def _generate_business_requirements(self) -> str:
        """Generate business requirements table"""
        requirements_md = """## 4. Business Requirements

| Priority Level | Critical Level | Requirement Description |
|---|---|---|
| High | Must | System shall collect and validate customer requirements from market research |
| High | Must | System shall define measurable business objectives aligned with market opportunity |
| High | Must | System shall document functional behaviors in testable format |
| Medium | Should | System shall maintain audit trail of requirement changes and approvals |
| Medium | Should | System shall provide stakeholder communication and reporting capabilities |
| Medium | Should | System shall accommodate market-driven requirement adjustments |
| Low | Could | System shall support multi-stakeholder requirement prioritization |
| Low | Could | System shall generate requirement traceability documentation |"""
        
        return requirements_md
    
    def _generate_key_stakeholders(self) -> str:
        """Generate key stakeholders table"""
        stakeholders_md = """## 5. Key Stakeholders

| Name | Job Role | Duties |
|---|---|---|
| Project Manager | Business Leadership | Strategic oversight, decision authority, resource allocation |
| Product Owner | Product Management | Requirements definition, prioritization, success metrics |
| Market Analyst | Market Research | Customer needs assessment, competitive analysis, market validation |
| Business Sponsor | Executive Management | Budget approval, strategic alignment, executive reporting |
| Customer Representative | Customer Interface | Requirements validation, feedback collection, acceptance criteria |
| Technical Lead | Technical Management | Feasibility assessment, constraint identification, risk management |
| Finance Officer | Financial Management | Budget planning, cost tracking, ROI monitoring |"""
        
        return stakeholders_md
    
    def _generate_project_constraints(self) -> str:
        """Generate project constraints table"""
        risk_level = self.analysis_data.get('risk_level', 'medium').lower()
        domain_tags = self.analysis_data.get('domain_tags', ['General Business'])
        
        constraints_md = f"""## 6. Project Constraints

| Constraint | Description |
|---|---|
| Timeline | Requirements analysis phase: 4–6 weeks. Market validation: ongoing. |
| Budget | To be determined based on scope and resource requirements. |
| Market Dependency | Success dependent on {domain_tags[0] if domain_tags else 'market'} market conditions and customer demand. |
| Stakeholder Availability | Requires consistent stakeholder engagement for requirements validation. |
| Data Dependency | Dependent on accurate market research and customer feedback collection. |
| Risk Tolerance | Current risk classification: {risk_level.upper()}. Requires risk mitigation strategy. |
| Regulatory Compliance | Must comply with applicable industry and operational regulations. |"""
        
        return constraints_md
    
    def _generate_cost_benefit_analysis(self) -> str:
        """Generate cost-benefit analysis table with ROI calculation"""
        compatibility_score = self.analysis_data.get('compatibility_score', 50)
        
        analysis_md = """## 7. Cost-Benefit Analysis

| Cost | Benefit |
|---|---|
| Requirements analysis and validation | Clear, measurable business objectives |
| Stakeholder engagement and communication | Aligned organizational understanding |
| Market research and customer discovery | Validated customer needs and market demand |
| Documentation and process establishment | Auditable requirements and change management |
| Team training and capability building | Enhanced business analysis capability |
| Ongoing market monitoring | Sustained competitive differentiation |"""
        
        analysis_md += f"""

### Financial Projection

**Total Direct Costs:** To be calculated based on resource allocation and timeline

**Identified Benefits:** 
- Reduced requirement ambiguity and rework
- Improved stakeholder alignment and decision velocity
- Measurable market opportunity validation
- Risk mitigation through structured analysis

**Expected ROI:** Qualitative assessment indicates positive return through improved project execution and reduced market entry risk. Numeric ROI should be calculated upon project completion based on actual outcomes achieved.

**Viability Score:** {compatibility_score}/100 - {self._get_viability_rating(compatibility_score)} indicates {self._get_investment_recommendation(compatibility_score)} investment recommendation."""
        
        return analysis_md
    
    def _get_viability_rating(self, score: int) -> str:
        """Convert score to viability rating"""
        if score >= 80:
            return "Excellent"
        elif score >= 60:
            return "Good"
        elif score >= 40:
            return "Fair"
        else:
            return "Needs Development"
    
    def _get_investment_recommendation(self, score: int) -> str:
        """Convert score to investment recommendation"""
        if score >= 80:
            return "Strong"
        elif score >= 60:
            return "Moderate"
        elif score >= 40:
            return "Conditional"
        else:
            return "Limited"


def generate_brd(analysis_data: Dict[str, Any], format: str = "txt") -> tuple:
    """
    Main function to generate BRD in specified format
    
    Args:
        analysis_data: Analysis results from AI engine
        format: Output format (pdf, docx, txt, image)
    
    Returns:
        (file_buffer, file_extension, mime_type)
    """
    
    # Validate format
    valid_formats = ['pdf', 'docx', 'txt', 'image']
    if format not in valid_formats:
        format = 'txt'
    
    logger.info(f"Generating BRD in {format} format")
    
    # Generate BRD content
    generator = BRDGenerator(analysis_data)
    brd_content = generator.generate_txt()
    
    # Export to requested format
    exporter = BRDExporter()
    
    if format == 'pdf':
        buffer = exporter.to_pdf(brd_content)
        return buffer, 'pdf', 'application/pdf'
    elif format == 'docx':
        buffer = exporter.to_docx(brd_content)
        return buffer, 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    elif format == 'image':
        buffer = exporter.to_image(brd_content)
        return buffer, 'png', 'image/png'
    else:  # txt
        buffer = exporter.to_text(brd_content)
        return buffer, 'txt', 'text/plain'
